[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static", "-C", "link-arg=-T", "-C", "link-arg=kernel/linker.ld"]
